### ISSUE TITLE
INFO Foto e Album  da sistemare

### ISSUE THREAD

**Issue by Mabol** [Mabol/Boogada#10]
Indichiamo i percorsi dove cliccando su una foto u su un album, compaiono info sbagliate di chi ha inserito la stessa/o

Cioè dove compare , ad esemio, nome utente anzichè nome della squadra pro

**Comment by PierpaoloB** [comment]
SQUADRA PRO --> PHOTO --> ALBUM --> ALBUM X --> FOTO (theatre)
SQUADRA PRO --> PHOTO --> FOTO SQUADRA --> FOTO (theatre)

HOME --> PHOTO --> FOTO (pagina)

**Comment by Mabol** [comment]
fatto
