### ISSUE TITLE
Dettaglio foto - manca titolo della foto in modalità theater

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#11]
Aprendo la foto da SQUADRA PRO --> PHOTO --> ALBUM X --> DETTAGLIO FOTO

**Comment by Mabol** [comment]
1- il titolo nella versione non delle squadre spunta? se si dove? se no glielo vuoi far spuntare dove?
2-ma la modalità theatre la vuoi togliere o migliorare?

**Comment by Mabol** [comment]
Comunque fatto!

**Comment by PierpaoloB** [comment]
Theater via!
