### ISSUE TITLE
Formazioni squadre pro

### ISSUE THREAD

**Issue by Mabol** [Mabol/Boogada#15]
Interfacciamento fra js e il foxe
integrazione copn nuovo modulo formazioni generale

**Comment by Mabol** [comment]
js quasi terminato

**Comment by PierpaoloB** [comment]
In attesa del grafico, per me potremmo investire 5 euro e prenderci una di queste robe già fatte che dici?

http://it.depositphotos.com/24067187/stock-illustration-Soccer-field-layout-with-formation.html?sst&sqc=60&sqm=2693&sq=2kfvsl

http://it.depositphotos.com/11804938/stock-illustration-Grunge-soccer-playing-field.html?sst=100&sqc=162&sqm=2693&sq=2kfvsl

http://it.depositphotos.com/35289625/stock-illustration-Soccer-field-illustration.-Football-tactics-and-strategy---popular--team-formation..html?sst=100&sqc=121&sqm=2693&sq=2kfvsl

http://it.depositphotos.com/30235149/stock-illustration-Football-tactics.html?sst&sqc=23&sqm=30&sq=2kfwex

CAMPI SPORTIVI IN GENERE

http://it.depositphotos.com/7034664/stock-illustration-Sport-fields-and-courts.html?sst&sqc=75&sqm=105&sq=2kfwmj

**Comment by Mabol** [comment]
link al primo js elaborato :
http://nicozza22.it/boogada/

**Comment by PierpaoloB** [comment]
Sfondo per formazioni: http://www.shutterstock.com/it/pic-13375189/stock-photo-perspective-view-of-an-empty-soccer-field-d-rendering.html?src=6QLUws7JBFFWbyZz4EKYrg-1-46

**Comment by Mabol** [comment]
Finito!
