### ISSUE TITLE
Modalità Theater

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#20]
Eliminarla e utilizzare solo la visualizzazione delle foto in pagina, se possibile

**Comment by Mabol** [comment]
quindi tolgierla propio? viaulizzazione solo nella pagina con commenti sotto?

**Comment by PierpaoloB** [comment]
esatto.. a me fa abbastanza cagare

**Comment by Mabol** [comment]
Fatto, chiudo.

Se invece a seguire il theatre mode lo vuoi tenere e semplicemente migliorare riaprilo.
