### ISSUE TITLE
WALL - commenti

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#53]
Non compaiono i commenti, come se non li registrasse in DB. 
Viene pubblicato ma quando si fa refresh di pagina scompare

**Comment by Mabol** [comment]
ma dove? io li vedo tutti

**Comment by PierpaoloB** [comment]
io non li vedo...

**Comment by Mabol** [comment]
chiarito che i commenti sono commenti di commenti, a breve sistemo anche questi

**Comment by Mabol** [comment]
risolto
