### ISSUE TITLE
News in evidenza

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#59]
OBIETTIVO: Creare in ciascuna pagina news (News di boogada, News di singola squadra o torneo, News di utente/pagina/blog) un blocco di news in evidenza

CHI METTE IN EVIDENZA LA NEWS: 

Nelle pagine News correlate a pagina/blog/utenti saranno gli admin della pagina
Nelle pagine delle squadre pro e dei tornei pro creati/gestiti da Boogada, sarà l'admin della squadra a metterle in evidenza (o il partner dove avesse pieno controllo sulla squdara)
Nella sezione News generale di Boogada sarà un admin Boogada

Note:
- una news potrebbe essere in evidenza nella pagina squadra, ma non nella pagina News di Boogada, quindi l'attribuzione di evidenza va scelta per le diverse pagine dove la news viene distribuita

**Comment by Mabol** [comment]
Sorpassato
