### ISSUE TITLE
Share - autore dell'elemento è errato (Admin e non Squadra Pro)

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#62]
Autore dell'elemento creato non appare correttamente, dovrebbe comparire il nome della squadra pro mentre compare l'utente admin.

Lo share è stato fatto, con lo stesso risultato, da:

Dettaglio elemento
Wall Boogada
Wall Squadra

![bug nome utente_squadra nel social share](https://f.cloud.github.com/assets/5991334/1963167/52a3e1ca-8296-11e3-9843-b3598cd95c3e.jpg)

**Comment by Mabol** [comment]
Risolto, basta cambiare la meta description perchè facebook prende quella.
ATTENZIONE che facebook ha una cache assurda quindi le foto che lui ha già memorizzato come share non avranno la modifica attuata
