### ISSUE TITLE
Pagina profilo Admin

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#66]
Nello stream compaiono anche le attività postate come Squadra PRO.. si possono oscurare?

http://www.boogada.com/profile-14/

**Comment by Mabol** [comment]
non ha molto senso, come boogada Pier vedi tutte le squadre pro, ma se sei utente normale vedi quelli che hai scritto come pagina

**Comment by PierpaoloB** [comment]
Oscuriamo i profili di admin allora!

**Comment by Mabol** [comment]
Fatto, adesso nei profili degli admin si vedono solo feed utente se ci va altro, mentre nel proprio si vedono tutti
