### ISSUE TITLE
Pagine

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#69]
http://www.boogada.com/pages/

Farei questi miglioramenti,come indicato nello screenshot:
1) Compattamento dell'elemento gruppo
2) Esploderei le categorie di lato
3) Per riempire le colonne banner! :D

![pagine gruppi rev](https://f.cloud.github.com/assets/5991334/2355550/cbf5d95c-a5dc-11e3-86f8-9443eacbfbe6.jpg)

**Comment by Mabol** [comment]
quelle sono le 4 categorie di inserimento, non è possibile farne di più oppure bisogna lavorarci non poco.

**Comment by PierpaoloB** [comment]
ok!

**Comment by Mabol** [comment]
Per ora chiudo!
