### ISSUE TITLE
Esplosione menu "Actions" (per l'utente che ha caricato la foto) nel dettaglio foto

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#7]
Farlo comparire già aperto con le varie opzioni (aggiungendoci magari il tasto "aggiungi foto come da #6 ).

**Comment by Mabol** [comment]
Ma considera che se sei admin ne hai di tastini e se non lo sei lo vedi solo nelle tue foto, non credo sia una cosa che porti valore aggiunto. Pensala sempre come utente non come admin

**Comment by PierpaoloB** [comment]
Non lo sopporto quel menù!!!! cque si essendo solo per admin meglio non
perderci tempo

**Comment by Mabol** [comment]
Allora chiudo e taggo abbandonato
