### ISSUE TITLE
Menu Boogada

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#70]
Io lo modificherei cosi

![menu boogada](https://f.cloud.github.com/assets/5991334/2395372/716581be-a9c8-11e3-876e-c621c55e7bd9.jpg)

Due appunti:
- Home andrà modificata come da interaction che abbiamo visto insieme
- Squadre Pro idem
- Boogazine va messa nel menù perchè è la pagina ufficiale della redazione, va fatto capire che è ufficiale e che sarà punto di riferimento inziale.. poi in un secondo momento potremmo anche toglierla
- Avevo pensato ad una voce "Campionati" momentanea, con un sottomenu che porta a Serie A (pagina gestita da noi), Serie B (pagina gestita da noi) o altre eventuali (Liga, Bundesliga).. ma in realtà potremmo mettere questi link nella pagina "Squadre PRO" che dici?

**Comment by Mabol** [comment]
Modificata Home, Squadre Pro, inserito BoogaZine, ABout, non contatti che non mi sembra abbia senso mettere in alto , rimane in footer. Per i campionati devo fare modulo che sarà poi tornei quindi quando sviluppo i tornei ci saraà.

Per ora quindi chiudo.
