### ISSUE TITLE
Layout pagina index NEWS

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#71]
Concetti: 
- mostrare più contenuti possibile al primo scroll  --> cambiare visualizzazione di primi
- mostrare più contenuti possibili in generale --> stringere e asciugare feed
- abstract notizie serve a poco o nulla qui  --> qui lo possiamo cassare

![nuovanews 4](https://f.cloud.github.com/assets/5991334/2482351/95167e8c-b0ea-11e3-9e5c-547cf9edff93.jpg)
![nuovanews 3](https://f.cloud.github.com/assets/5991334/2482352/951f6902-b0ea-11e3-8cc9-f70820e9b524.jpg)

**Comment by Mabol** [comment]
Fatto
