### ISSUE TITLE
Menu Boogada - 02maggio

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#72]
"Squadre" al posto di "Squadre PRO" (poi dentro mettiamo la doppia oppure menu a tendina)

Via "amici", "eventi", e inserirei "Campionati", ovvero link alla index pagine filtrata per sottocategoria.. ci saranno solo serie A e Brasile all'inizio però per chi lo vede da fuori si comincia ad abituare

Poi cambierei ordine cosi:

HOME - NEWS - SQUADRE - CAMPIONATI - PAGINE - FORUM - BOOGAZINE -FOTO - VIDEO - UTENTI (o anche no quest'ultima voce)

**Comment by Mabol** [comment]
Fatto
