### ISSUE TITLE
Squadre PRO: Modifica box

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#73]
Sostiuire box con scritta "Scopri ed inserisci News, Foto, Video...." con immagine.
Si può? dimensioni?

Idem sotto!

---

Box squadre in evidenza:
ora so che mi meni... ringrandiamoli per farne stare 5 per riga! :/

**Comment by Mabol** [comment]
come ti dicevo le scritte le puoi cambiare a piacimento e l'immagine gliela infilo con html e css.
Per le squadrfe non ho capito, ma chiudo per sentirci in FB

**Comment by PierpaoloB** [comment]
ww
