### ISSUE TITLE
Hashtag

### ISSUE THREAD

**Issue by PierpaoloB** [Mabol/Boogada#8]
Vengono indicizzati con hashtag solo gli status.
Se pubblico una foto, una canzone, una domanda, un link e aggiungo hashtag nella descrizione non viene indicizzata

**Comment by Mabol** [comment]
Credo sia un problema proprio del fox, vedo se ci sono soluzioni , Priorità bassa

**Comment by Mabol** [comment]
Risolto e messo a posto
